---
abstract: 'Bootstrap your scripts'
author:
  - 'Nour Sharabash <amirite@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nour
requires:
  Carp: 0
  DBI: 0
  DBIx::Simple: 0
  Data::Dumper: 0
  File::Find: 0
  FindBin: 0
  IO::File: 0
  Moose: 0
  Moose::Role: 0
  YAML: 0
  feature: 0
  namespace::autoclean: 0
resources:
  bugtracker: https://github.com/quran/nour/issues
  repository: git://github.com/quran/nour.git
version: 0.01
